# Generated by Django 4.1.7 on 2023-04-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(default="nizar", max_length=20)),
                (
                    "Lieu",
                    models.CharField(
                        choices=[
                            ("pav1", "Pavillon 1"),
                            ("pav2", "Pavillon 2"),
                            ("pav3", "Pavillon 3"),
                            ("Ascensseur", "Ascensseur"),
                            ("autre", "Autre"),
                        ],
                        default="nizar",
                        max_length=10,
                    ),
                ),
                ("Num", models.IntegerField(default=0)),
                ("Description", models.TextField()),
                ("Pièce_jointe", models.FileField(null=True, upload_to="")),
            ],
        ),
    ]
