# Generated by Django 4.1.7 on 2023-04-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reclamation", old_name="Lieu", new_name="Lieu_concerné",
        ),
        migrations.RenameField(
            model_name="reclamation", old_name="Nom", new_name="Nom_complet",
        ),
        migrations.RenameField(
            model_name="reclamation", old_name="Num", new_name="Numéro_de_chambre",
        ),
    ]
