# Generated by Django 4.1.7 on 2023-04-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0002_rename_lieu_reclamation_lieu_concerné_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamation",
            name="Numéro_de_Téléphone",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reclamation",
            name="Numéro_de_chambre",
            field=models.IntegerField(null=True),
        ),
    ]
