# Generated by Django 4.1.7 on 2023-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0003_reclamation_numéro_de_téléphone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamation",
            name="Nom_complet",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="reclamation",
            name="Pièce_jointe",
            field=models.FileField(upload_to=""),
        ),
    ]
