# Generated by Django 4.1.7 on 2023-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0004_alter_reclamation_nom_complet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamation",
            name="Numéro_de_chambre",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="reclamation",
            name="Pièce_jointe",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
