# Generated by Django 4.1.7 on 2023-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0005_alter_reclamation_numéro_de_chambre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamation",
            name="Numéro_de_chambre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reclamation",
            name="Pièce_jointe",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
