# Generated by Django 4.1.7 on 2023-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0006_alter_reclamation_numéro_de_chambre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamation",
            name="time",
            field=models.DateField(auto_now=True),
        ),
    ]
