# Generated by Django 4.1.7 on 2023-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0008_remove_reclamation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamation",
            name="time",
            field=models.DateField(auto_now_add=True, default="2002-08-25"),
            preserve_default=False,
        ),
    ]
