# Generated by Django 4.1.7 on 2023-04-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0010_reclamation_terminer_reclamation_traitement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamation",
            name="terminer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reclamation",
            name="traitement",
            field=models.BooleanField(default=False),
        ),
    ]
