# Generated by Django 4.1.7 on 2023-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0011_alter_reclamation_terminer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamation",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
