# Generated by Django 4.1.7 on 2023-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0013_alter_reclamation_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suivi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
