# Generated by Django 4.1.7 on 2023-04-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0015_alter_suivi_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suivi", old_name="id", new_name="object_id",
        ),
    ]
