# Generated by Django 4.1.7 on 2023-04-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamation", "0016_rename_id_suivi_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamation",
            name="reparer",
            field=models.BooleanField(default=False),
        ),
    ]
